version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    environment:
      - PORT=5000

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - server
